<?php
/* @var $this \lib\base\View */
?>
<header id="header">
    <div class="container">
        <div id="logo" class="col-12">
            <a href="#hero"><img src="<?= $this->toUrl('logo-ft.png'); ?>" style="max-width: 80px" alt="" title=""/></a>
        </div>
    </div>
</header><!-- #header -->

<!--==========================
  Hero Section
============================-->
<section id="hero">
    <div class="hero-container">
        <h1>Welcome to Regna</h1>
        <h2>Please enter the link to create the shortest link!</h2>
        <div class="container">
            <form class="" action="" method="post">
                <div class="row">
                    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
                        <textarea id="textarea" onkeyup="textAreaAdjust(this)" style="overflow:hidden" class="form-control w-100" id="url" placeholder="Please enter a long link and click generate"
                                  name="original_url"><?= $this->settings->url; ?></textarea>
                        <div class="col-12 text-center pt-3 px-0">
                            <button type="submit" class="btn btn-success text-center w-100">Generate</button>
                        </div>

                    </div>
                </div>
                <?php
                if (isset($this->settings->code)){
                ?>
                <div class="row my-3 pt-4">
                    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
                        <div class="row">
                            <div class="col-8 text-right pr-0"><input id="myInput" readonly class="form-control" value="<?= $this->settings->code ?>"></div>
                            <div class="col-4"><button type="button" id="copy" class="btn btn-danger text-center w-100" data-toggle="tooltip" title="Copy to clipboard">Copy</button></div>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </form>
        </div>
    </div>
</section><!-- #hero -->

<!--==========================
  Footer
============================-->
<footer id="footer">
    <div class="footer-top">
        <div class="container">

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>Jobs Vina</strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="http://jobsvina.com" target="_blank">Jobs Vina</a>
        </div>
    </div>
</footer><!-- #footer -->

<script>
    $('#copy').on('click', function (e) {
        var copyText = document.getElementById("myInput");
        copyText.select();
        document.execCommand("copy");
        $('body').find('.tooltip .tooltip-inner').html('Text copied !')
    });

    function textAreaAdjust(o) {
        o.style.height = "1px";
        o.style.height = (25+o.scrollHeight)+"px";
    }

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        var _textarea = $('#textarea');
        if ($.trim(_textarea.val()) == '') {
            _textarea.focus();
        }
    });
</script>