<?php
/* @var $this \lib\base\View */
?>
<style>
	#logos .row > div a.img{ min-height: 80px; display: block;}
	#logos .row > div a p{ font-size: 11px;}
</style>
<section id="hero">
    <div class="hero-container">
        <h1 class="mt-0">Chào mừng đến với Url Zip</h1>
        <h2>Hãy nhập liên kết của bạn vào ô bên dưới để tạo liên kết ngắn gọn hơn!</h2>
        <div class="container mb-5">
            <form class="" action="" method="post">
                <div class="row">
                    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
                        <textarea id="textarea" onkeyup="textAreaAdjust(this)"
                                  style="overflow:hidden" class="form-control w-100"
                                  id="url"
                                  placeholder="Hãy nhập liên kết dài vào đây và nhấn [Tạo liên kết]"
                                  name="original_url"><?= $this->settings->url; ?></textarea>
                        <div class="col-12 text-center pt-3 px-0">
                            <button type="submit" class="btn btn-success text-center w-100">Tạo liên kết</button>
                        </div>
                    </div>
                </div>
                <?php
                if (isset($this->settings->code)){
                ?>
                <div class="row my-3 pt-4 mx-0">
                    <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
                        <div class="row">
                            <div class="col-8 text-right pr-0"><input id="myInput" readonly class="form-control" value="<?= $this->settings->code ?>"></div>
                            <div class="col-4"><button type="button" id="copy" class="btn btn-danger text-center w-100" data-toggle="tooltip" title="Copy vào clipboard">Copy</button></div>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </form>
        </div>

	    <div class="row mx-0 px-5 mt-md-4 mt-lg-5">
		    <div id="logos" class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3 px-0 mt-lg-5">
			    <div class="row">
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4">
					    <a href="https://jobsvina.com" target="_blank" class="img">
						    <img src="<?= $this->toUrl('logo-ft.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
					    <a href="https://jobsvina.com" target="_blank">
					        <p class="pt-2 mb-0">Tìm kiếm việc làm miễn phí</p>
					    </a>
				    </div>
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4">
					    <a href="https://ec-cube.vn" target="_blank" class="img">
						    <img src="<?= $this->toUrl('web/img/ec-cube.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
					    <a href="https://jobsvina.com" target="_blank">
						    <p class="pt-2 mb-0">Mã nguồn mở website TMĐT</p>
					    </a>
				    </div>
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4" data-placement="bottom" data-toggle="tooltip" title="Liên hệ đặt quảng cáo: Toàn - nguyennguyen.vt88@gmail.com">
					    <a href="#" class="img">
						    <img src="<?= $this->toUrl('web/img/logo.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
				    </div>
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4">
					    <a href="#">
						    <img src="<?= $this->toUrl('web/img/logo.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
				    </div>
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4">
					    <a href="#">
						    <img src="<?= $this->toUrl('web/img/logo.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
				    </div>
				    <div class="col-6 col-sm-4 col-md-2 col-lg-2 mb-4">
					    <a href="#">
						    <img src="<?= $this->toUrl('web/img/logo.png'); ?>" class="w-100" alt="Image" style="max-width:100%;">
					    </a>
				    </div>
			    </div>
		    </div>
	    </div>
    </div>
</section>
<footer id="footer">
    <div class="footer-top">
        <div class="container">

        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>Jobs Vina</strong>. All Rights Reserved
        </div>
    </div>
</footer><!-- #footer -->

<script>
    $('#copy').on('click', function (e) {
        var copyText = document.getElementById("myInput");
        copyText.select();
        document.execCommand("copy");
        $('body').find('.tooltip .tooltip-inner').html('Đã copy vào clipboard!')
    });

    function textAreaAdjust(o) {
        o.style.height = "1px";
        o.style.height = (25 + o.scrollHeight) + "px";
    }

    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
        var _textarea = $('#textarea');
        if ($.trim(_textarea.val()) == '') {
            _textarea.focus();
        }
    });
</script>