<?php
/* @var $this \lib\base\View */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Short link</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="logo-ft.png" rel="icon">
    <link href="logo-ft.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="<?= $this->toUrl('web/Regna/lib/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="<?= $this->toUrl('web/Regna/lib/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->toUrl('web/Regna/lib/animate/animate.min.css'); ?>" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="<?= $this->toUrl('web/Regna/css/style.css'); ?>" rel="stylesheet">
	<script src="<?= $this->toUrl('web/Regna/lib/jquery/jquery.min.js'); ?>"></script>
	<script src="<?= $this->toUrl('web/Regna/lib/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
</head>

<body>
<?php echo $this->content(); ?>
<?php $this->printScripts(); ?>
</body>
</html>
