<?php
/* @var $this \lib\base\View */
?>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <title>Tạo liên kết ngắn gọn | Url Zip</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <meta name="robots" content="index,follow">
    <meta name="copyright" content="index,follow">
    <meta property="og:type" content="Tạo liên kết ngắn gọn"/>
    <meta property="og:title" content="Tạo liên kết ngắn gọn, short link| Url Zip"/>
    <meta property="og:url" content="/"/>
    <meta property="og:description" content="Tạo liên kiết ngắn gọn cho url, liên kết dài dòng"/>
    <meta property="article:published_time" content="Jan 1, 2018"/>
    <meta property="article:modified_time" content="Apr 10, 2019"/>
    <meta property="og:site_name" content="https://urlzp.com"/>
    <meta property="og:image" content="/favicon.ico?w=200"/>
    <meta property="og:image:width" content="200"/>
    <meta property="og:image:height" content="200"/>
    <meta property="og:locale" content="vi_VN"/>
    <meta name="twitter:site" content="https://urlzp.com"/>
    <meta name="twitter:text:title" content="Tạo liên kiết ngắn gọn, đẹp cho url, liên kết dài dòng | Url Zip"/>
    <meta name="twitter:image" content="/favicon.ico?w=240"/>
    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:creator" content="Url Zip"/>
    <meta name="twitter:description" content="Tạo liên kiết ngắn gọn, đẹp cho url, liên kết dài dòng | Url Zip"/>
    <meta property="article:publisher" content="https://www.facebook.com/vina-jobs.com"/>
    <link href="favicon.png" rel="icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">
    <link href="<?= $this->toUrl('web/Regna/lib/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->toUrl('web/Regna/lib/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->toUrl('web/Regna/lib/animate/animate.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->toUrl('web/Regna/css/style.css'); ?>" rel="stylesheet">
	<script src="<?= $this->toUrl('web/Regna/lib/jquery/jquery.min.js'); ?>"></script>
	<script src="<?= $this->toUrl('web/Regna/lib/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-138062003-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-138062003-1');
    </script>
	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
	<script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-5817284333210875",
            enable_page_level_ads: true
        });
	</script>
</head>

<body>
<?php echo $this->content(); ?>
<?php $this->printScripts(); ?>
</body>
</html>
